[http.middlewares]
  [http.middlewares.set-host-header.headers]
    customRequestHeaders = { Host = "summer-gorilla-uy4l84j8.fra0.kraft.host" }

[http.routers]
  [http.routers.agent1]
    rule = "Path(`/agent1`)"
    service = "agent1-service"
    middlewares = ["set-host-header"]
    entryPoints = ["web"]

  [http.routers.agent1-docs]
    rule = "Path(`/agent1/docs`)"
    service = "agent1-service"
    middlewares = ["set-host-header"]
    entryPoints = ["web"]

  [http.routers.agent1-openapi]
    rule = "Path(`/agent1/openapi.json`)"
    service = "agent1-service"
    middlewares = ["set-host-header"]
    entryPoints = ["web"]

  [http.routers.rest]
    rule = "PathPrefix(`/`)"
    service = "rest-service"
    entryPoints = ["web"]

[http.services]
  [http.services.agent1-service.loadBalancer]
    [[http.services.agent1-service.loadBalancer.servers]]
      url = "https://summer-gorilla-uy4l84j8.fra0.kraft.host"

  [http.services.hello-service.loadBalancer]
    [[http.services.hello-service.loadBalancer.servers]]
      url = "http://localhost:9000"

  [http.services.rest-service.loadBalancer]
    [[http.services.rest-service.loadBalancer.servers]]
      url = "http://localhost:9001"